name: my_coma
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  http: ^0.13.3
  shared_preferences: ^2.0.9
  image_picker: ^0.8.5+3
  syncfusion_flutter_charts: ^28.2.11
  flutter_localizations:
        sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/background.jpg
flutter_intl:
  enabled: true
